server:
  port: 8083
spring:
  cloud:
    gateway:
      routes:
        - id: book-route
          uri: lb://book-service
          predicates:
            - Path=/book/**
          filters:
            - RewritePath=/book/(?<remaining>.*), /${remaining}


        - id: category-route
          uri: lb://category-service
          predicates:
            - Path=/category/**
          filters:
            - RewritePath=/category/(?<remaining>.*), /${remaining}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
