server:
  port: 8083
spring:
  cloud:
    gateway:
      routes:
        - id: book-route
          uri: lb://book-service
          predicates:
            - Path=/book/**
          filters:
            - name: AuthenticationFilter
              args:

        - id: category-route
          uri: lb://category-service
          predicates:
            - Path=/category/**
          filters:
            - name: AuthenticationFilter
              args:

        - id: security-route
          uri: lb://security-service
          predicates:
            - Path=/auth/**


        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
